version: '3.0'
services:
  app-barplot:
    build: .
    image: dashboard
    command: python app_barplot.py
    ports:
      - "8050:8050"
    volumes:
      - .:/home/myuser:rw
  app-histogram:
    image: dashboard
    command: python app_histogram.py
    ports:
      - "8080:8080"
    volumes:
      - .:/home/myuser:rw

